#!/bin/sh
set -eu

ROOT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
OUT_DIR="$ROOT_DIR/generated-config"

ask() {
  prompt="$1"
  default="${2:-}"
  if [ -n "$default" ]; then
    printf '%s [%s]: ' "$prompt" "$default"
  else
    printf '%s: ' "$prompt"
  fi
  read -r value
  if [ -z "$value" ]; then
    value="$default"
  fi
  printf '%s' "$value"
}

write_header() {
  file="$1"
  {
    echo "; Generated by scripts/install.sh"
    echo "; Review before copying to /etc/disown."
    echo
  } > "$file"
}

mkdir -p "$OUT_DIR"
cat > "$OUT_DIR/.htaccess" <<'EOF'
Require all denied
EOF

echo "BBS MDM Disown - Setup helper"
echo "This helper writes example runtime config files to:"
echo "$OUT_DIR"
echo

base_url=$(ask "Public base URL" "https://example.org/disown")
db_host=$(ask "Database host" "localhost")
db_name=$(ask "Database name" "disown")
db_user=$(ask "Database user" "disown_app")
db_password=$(ask "Database password" "")

smtp_host=$(ask "SMTP host" "smtp.example.org")
smtp_port=$(ask "SMTP port" "587")
smtp_user=$(ask "SMTP username" "mdm@example.org")
smtp_password=$(ask "SMTP password" "")
smtp_from=$(ask "SMTP from address" "$smtp_user")
smtp_encryption=$(ask "SMTP encryption (tls, ssl, none)" "tls")

notify_to=$(ask "Admin notification recipients, comma separated" "admin@example.org")
serial_token_secret=$(ask "Web Clip serial token secret" "")

oidc_issuer=$(ask "OIDC issuer" "https://mein-iserv.de")
oidc_client_id=$(ask "OIDC client id" "")
oidc_client_secret=$(ask "OIDC client secret" "")
oidc_admin_roles=$(ask "OIDC admin roles, comma separated" "MDM_ADMINS,ROLE_MDM_ADMINS")
oidc_viewer_roles=$(ask "OIDC viewer roles, comma separated" "MDM_VIEWERS")

jamf_url=$(ask "Jamf School URL" "https://schoolname.jamfcloud.com")
jamf_network_id=$(ask "Jamf network id" "")
jamf_api_key=$(ask "Jamf API key" "")

asm_client_id=$(ask "ASM client id" "")
asm_key_id=$(ask "ASM key id" "")
asm_team_id=$(ask "ASM team id" "")
asm_private_key=$(ask "ASM private key path" "/etc/disown/asm-private-key.pem")

write_header "$OUT_DIR/db.conf"
cat >> "$OUT_DIR/db.conf" <<EOF
DB_HOST=$db_host
DB_USER=$db_user
DB_PASSWORD=$db_password
DB_NAME=$db_name
EOF

write_header "$OUT_DIR/app.conf"
cat >> "$OUT_DIR/app.conf" <<EOF
REQUIRE_SERIAL_TOKEN=0
SERIAL_TOKEN_SECRET=$serial_token_secret
EOF

write_header "$OUT_DIR/mail.conf"
cat >> "$OUT_DIR/mail.conf" <<EOF
MAIL_HOST=$smtp_host
MAIL_PORT=$smtp_port
MAIL_USERNAME=$smtp_user
MAIL_PASSWORD=$smtp_password
MAIL_FROM=$smtp_from
MAIL_ENCRYPTION=$smtp_encryption
EOF

write_header "$OUT_DIR/notify.conf"
cat >> "$OUT_DIR/notify.conf" <<EOF
NOTIFY_TO=$notify_to
APP_URL=$base_url/admin
NOTIFY_LIMIT=50
NOTIFY_STATE_FILE=/var/lib/disown/notify-state.json
EOF

write_header "$OUT_DIR/oidc.conf"
cat >> "$OUT_DIR/oidc.conf" <<EOF
OIDC_ENABLED=1
OIDC_ISSUER=$oidc_issuer
OIDC_CLIENT_ID=$oidc_client_id
OIDC_CLIENT_SECRET=$oidc_client_secret
OIDC_SCOPES="openid email profile iserv:roles iserv:uuid"
OIDC_ALLOWED_EMAILS=""
OIDC_ALLOWED_ROLES="$oidc_admin_roles"
OIDC_VIEWER_ROLES="$oidc_viewer_roles"
EOF

write_header "$OUT_DIR/jamf.conf"
cat >> "$OUT_DIR/jamf.conf" <<EOF
JAMF_URL=$jamf_url
JAMF_NETWORK_ID=$jamf_network_id
JAMF_API_KEY=$jamf_api_key
EOF

write_header "$OUT_DIR/asm.conf"
cat >> "$OUT_DIR/asm.conf" <<EOF
ASM_CLIENT_ID=$asm_client_id
ASM_KEY_ID=$asm_key_id
ASM_TEAM_ID=$asm_team_id
ASM_PRIVATE_KEY=$asm_private_key
ASM_JWT_HELPER=/etc/disown/asm-jwt.py
EOF

cat > "$OUT_DIR/apache-protect.conf" <<EOF
# Example Apache protection rules. Adapt paths to your vhost.
<Directory "$ROOT_DIR/config">
    Require all denied
</Directory>
<Directory "$ROOT_DIR/vendor">
    Require all denied
</Directory>
<Directory "$ROOT_DIR/templates">
    Require all denied
</Directory>
<Directory "$ROOT_DIR/scripts">
    Require all denied
</Directory>
<Directory "$ROOT_DIR/generated-config">
    Require all denied
</Directory>
EOF

cat > "$OUT_DIR/cron.example" <<EOF
30 7,13 * * 1-5 www-data /usr/bin/php $ROOT_DIR/notify_admins.php >> /var/log/disown/notify.log 2>&1
29 7,13 * * * www-data /usr/bin/php $ROOT_DIR/sync_ade_enrollments.php --days=90 >> /var/log/disown/ade-sync.log 2>&1
EOF

chmod 600 "$OUT_DIR"/*.conf

echo
echo "Generated files:"
ls -1 "$OUT_DIR"
echo
echo "Next steps as root:"
echo "  install -d -m 750 /etc/disown /var/lib/disown /var/log/disown"
echo "  install -m 640 $OUT_DIR/*.conf /etc/disown/"
echo "  setfacl -m u:www-data:r /etc/disown/*.conf"
echo
echo "Then run:"
echo "  composer install --no-dev --optimize-autoloader"
echo "  php scripts/check_requirements.php"
